export const pagesRoutes = [
  ["v-184f4da6","/intro.html",{"y":"p","t":"关于我","I":false},[":md"]],
  ["v-8daa1a0e","/",{"y":"h","t":"主页","i":"home"},["/README.md"]],
  ["v-14f724bf","/mood/",{"y":"p","t":"随笔"},["/mood/README.md"]],
  ["v-4ef77674","/studynotes/1.html",{"d":1697328000000,"l":"2023年10月15日","c":["笔记"],"e":"关于GittePage的一个简单记录","y":"a","t":"Gitee部署静态网站"},[":md"]],
  ["v-4b8dc536","/studynotes/2.html",{"d":1697760000000,"l":"2023年10月20日","c":["笔记"],"g":["Taro"],"e":"<h1> 关于Taro开发环境路径异常的一些记录</h1>\n<div class=\"language-text line-numbers-mode\" data-ext=\"text\"><pre class=\"language-text\"><code>环境信息：\n    \"react\": \"^18.0.0\",\n    \"react-dom\": \"^18.0.0\",\n    \"taro-ui\": \"^3.1.1\",\n    \"@tarojs/taro\": \"3.6.18\",\n    NodeJs：V18.17.0\n</code></pre><div class=\"line-numbers\" aria-hidden=\"true\"><div class=\"line-number\"></div><div class=\"line-number\"></div><div class=\"line-number\"></div><div class=\"line-number\"></div><div class=\"line-number\"></div><div class=\"line-number\"></div></div></div>","y":"a","t":"关于Taro开发环境路径异常的一些记录"},[":md"]],
  ["v-482413f8","/studynotes/3.html",{"e":"<h1> GitHub Pages 托管静态页面</h1>\n<blockquote>\n<p>Github</p>\n<p>Node</p>\n<p>Git</p>\n</blockquote>\n<p>新建一个github 仓库</p>\n<figure><figcaption></figcaption></figure>\n<p>使用小乌龟 Commit代码</p>\n<figure><figcaption></figcaption></figure>\n","y":"a","t":"GitHub Pages 托管静态页面"},[":md"]],
  ["v-3e65f804","/studynotes/",{"y":"p","t":"笔记"},["/studynotes/README.md"]],
  ["v-3706649a","/404.html",{"y":"p","t":""},[]],
  ["v-5bc93818","/category/",{"y":"p","t":"分类","I":false},[]],
  ["v-744d024e","/tag/",{"y":"p","t":"标签","I":false},[]],
  ["v-e52c881c","/article/",{"y":"p","t":"文章","I":false},[]],
  ["v-154dc4c4","/star/",{"y":"p","t":"收藏","I":false},[]],
  ["v-01560935","/timeline/",{"y":"p","t":"时间轴","I":false},[]],
  ["v-49425445","/category/%E7%AC%94%E8%AE%B0/",{"y":"p","t":"笔记 分类","I":false},["/category/笔记/"]],
  ["v-292eb677","/tag/taro/",{"y":"p","t":"标签: Taro","I":false},[]],
]
